# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg12345
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"
#    environment:
#      POSTGRES_URL: jdbc:postgresql://db:5432/postgres
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
